version: "2.1"

services:
    elasticsearch:
        image: elasticsearch:7.6.2
        container_name: wiki_elasticsearch
        ports:
            - "9200:9200"
            - "9300:9300"
        environment:
            - discovery.type=single-node
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - "elastic_lucene:/usr/share/elasticsearch/data"
        healthcheck:
            test: ["CMD", "curl", "-f", "localhost:9200/_cluster/health?wait_for_status=yellow&timeout=120s&pretty"]
            interval: 15s
            timeout: 10s
            retries: 8
    backend:
        container_name: backend
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        depends_on:
            elasticsearch:
                condition: service_healthy
    logstash:
        image: logstash:7.6.2
        container_name: wiki_logstash
        user: root
        command: sh -c "exec /mnt/datasource.sh"
        volumes:
            - "./datasource/:/mnt/"
            - "./logstash/pipeline/enwikibooks.conf:/usr/share/logstash/pipeline/logstash.conf"
        ports:
            - "5000:5000"
            - "9600:9600"
    # comment if you dont want to explore lucene indexes
    kibana:
        image: kibana:7.6.2
        container_name: wiki_kibana
        ports:
            - "5601:5601"
    swagger:
        container_name: swagger
        image: swaggerapi/swagger-ui
        ports:
            - "8081:8080"
        volumes:
            - "./swagger:/swagger"
        environment:
            - SWAGGER_JSON=/swagger/wikisniffer.yml
    frontend:
        container_name: frontend
        build:
            context: frontend
            dockerfile: Dockerfile
        ports:
            - "9090:80"
volumes:
    elastic_lucene:
