export default {
    SET_SEARCH_QUERY: 'SET_SEARCH_QUERY',
    SET_SEARCH_DATA: 'SET_SEARCH_DATA',
    SET_SEARCH_RESULTS: 'SET_SEARCH_RESULTS',
    APPEND_MORE_RESULTS: 'APPEND_MORE_RESULTS',
    INCREASE_SEARCH_PAGE: 'INCREASE_SEARCH_PAGE',
    CLEAR_SEARCH: 'CLEAR_SEARCH'
}
