export default {
    SET_SEARCH_QUERY: 'SET_SEARCH_QUERY',
    SET_SEARCH_DATA: 'SET_SEARCH_DATA',
    SET_SEARCH_BODY: 'SET_SEARCH_BODY',
    SET_SEARCH_RESULTS: 'SET_SEARCH_RESULTS',
    APPEND_MORE_RESULTS: 'APPEND_MORE_RESULTS',
    INCREASE_SEARCH_PAGE: 'INCREASE_SEARCH_PAGE',
    CLEAR_SEARCH: 'CLEAR_SEARCH',
    RESET_SEARCH_PAGE_NUMBER: 'RESET_SEARCH_PAGE_NUMBER',
    SET_FULL_SCREEN_LOADER: 'SET_FULL_SCREEN_LOADER',
    CLEAR_FULL_SCREEN_LOADER: 'CLEAR_FULL_SCREEN_LOADER',
}
